project:
  type: website

website:
  title: "SIGERIP"
  navbar:
    logo: img.jpg
    left:
      - href: index.qmd
        text: Home
      - mortalidade.qmd
      - modelos.qmd
    right:  
      - icon: github
        href: https://github.com/isaiasfelipe01
      - icon: instagram
        href: https://www.instagram.com/sigerip.ufpb/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



